### ISSUE TITLE
Validation failed: Phone number is invalid <--- need graceful failure

### ISSUE THREAD

**Issue by dan-mi-sun** [blockades/mmt#24]
When you put in a phone number incorrectly (such as missing a digit) fail through to the rails ActiveRecord page.

Suggest we capture this with a simpler page or possibly check the fields with js client side... (although I prefer us not to only rely on JS)

> ActiveRecord::RecordInvalid in Members::TwoFactorController#create

**Comment by KGibb8** [comment]
Resolved https://github.com/blockades/mmt/pull/41
