### ISSUE TITLE
docker-compose up fails with database 'db' does not exist

### ISSUE THREAD

**Issue by ameba23** [blockades/mmt#37]
### Steps to reproduce

1. docker-compose build 
2. docker-compose up
3. 

### Expected behavior
mmt, postgres and redis run

### Actual behavior
postgres starts up fine, but then says:
```
db_1     | FATAL:  database "db" does not exist
```
but 'db', as i understand, is the name of the postgres container, not the name of the database.

could this be something to do with that in docker-compose.yml we have:
```
environment:
      DATABASE_URL: db
```
is this correct?  is it working for you?

### ENVIRONMENT
Arch: x64 
docker-compose version 1.17.0, build ac53b73
Docker version 17.11.0-ce, build 1caf76ce6b

**Comment by sadeden** [comment]
@ameba23 are you up-to-date ? Because  env configuration in docker-compose.yml looks like this : 
```
    environment:
      DATABASE_URL: postgres

```
Here https://github.com/blockades/mmt/blob/feature/dockerize/docker-compose.yml#L30

**Comment by sadeden** [comment]
@ameba23 are you up-to-date ? Because  env configuration in docker-compose.yml looks like this : 
```
    environment:
      DATABASE_URL: postgres

```
Here

**Comment by KGibb8** [comment]
Sorry I resolved this and posted in Keybase. Didn't realise it was an issue here. Wondering if we've too many discussion channels :neutral_face:
